version: '3'

services:
  web:
    environment:
      - DJANGO_SECRET_KEY='#6voslr*jj!l6=oxb5bx%@@$$9tzp562rp)01x=!5pagegh!dw0'
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

